name: Build LaTeX documents

on:
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX to PDF
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./compile.sh

      - name: Archive pdf:s
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            **/*.pdf

      # We build a bunch of low-res png:s in order to compare them to the original ones.
      - name: Install image utils
        run: sudo apt-get install -y poppler-utils imagemagick

      - name: Generate png:s from pdf:s
        run: ./.github/scripts/img.sh

      - name: Archive png:s
        uses: actions/upload-artifact@v2
        with:
          name: pngs
          path: |
            **/*.pdf-*.png
      
      - name: Compare png:s to original png:s
        run: ./.github/scripts/img_cmp.sh
