name: Build LaTeX documents
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run compile.sh
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./compile.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            **/*.pdf