# This is a basic workflow to help you get started with Actions

name: Parse into JSON

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Syntax-check TeX files
        run: |
          cd parser 
          python3 linter.py
      
      - name: Run JSON converter (experimental)
        run: |
          cd parser 
          python3 main.py
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out.json
          path: |
            parser/out.json