# This is a basic workflow to help you get started with Actions

name: Parse into JSON

# Controls when the workflow will run
on: [push]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Syntax-check TeX files
        run: |
          cd parser 
          python3 linter.py

  parse-to-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run JSON converter (experimental)
        run: |
          cd parser 
          python3 main.py
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out.json
          path: parser/out.json